name: Format Python Code

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black
      id: black
      run: black .

    - name: Commit and push changes
      if: ${{ steps.black.outcome == 'success' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'Pshiv13'
        git config --global user.email 'pshiv13798@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git add .
        git commit -m 'Apply Black code formatting'
        git push origin HEAD:${{ github.ref }}
