name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Run OWASP Dependency Check
      run: |
        docker pull owasp/dependency-check
        docker run --rm \
          -v $(pwd):/src \
          -v $(pwd)/odc-reports:/report \
          owasp/dependency-check \
          --scan /src \
          --format "ALL" \
          --out /report \
          --project "My Python Project"

    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: odc-reports
