name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Manually trigger workflow from GitHub UI

jobs:
  sonarcloud_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you are using

    - name: Install SonarCloud Scan
      run: |
        python -m pip install --upgrade pip
        pip install pylint  # Install any necessary packages
        pip install coverage  # Install any necessary packages
        pylint **/*.py

    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: sonar-scanner || true  # Continue even if SonarCloud analysis fails

    - name: Check SonarCloud Analysis Status
      run: |
        # Add any post-analysis checks or commands here
        echo "SonarCloud analysis completed."

    - name: Finalize
      if: always()  # Always run this step regardless of previous steps' outcomes
      run: echo "Pipeline completed."

